services:
  arena:
    build: .
    container_name: arena_haxball
    restart: unless-stopped
    env_file: .env
    environment:
      - CHROMIUM_PATH=/usr/bin/chromium
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./data.db:/app/data.db
      - ./clips:/app/clips
    shm_size: 256mb
    cpu_shares: 2048
    cpus: "3.0"
    mem_limit: 8g
    mem_reservation: 4g
